### ISSUE TITLE
Git vs Github

### ISSUE THREAD

**Issue by nishp1** [apexa11/Toodo#1]
Question: What is the difference between Git and Github?

**Comment by apexa11** [comment]
Answer: GIT : Git is distributed version control system. Git is responsible for keeping track of changes to content, and it provides mechanisms for sharing that content with others. it handle everything from small to very large projects with speed and efficiency".

GITHUB:GitHub is a company that provides Git repository hosting. If any team has a shared repository on GitHub, you could conceivably use GitHub without ever looking at its website.
GitHub also developed graphical Git clients: GitHub for Mac and GitHub for Windows. Each is an application that lets you interact with Git repositories without using the command line.

**Comment by nishp1** [comment]
What do following commands do?
- `git status`
- `git commit -am`
- `git commit -m`
- `git add`
- `git remove`
- `git push`

**Comment by apexa11** [comment]
git status: git status shows you STATUS of files in index versus working directory.
                 it will list out that files which are UNTRACKED, MODIFIED  and files which are added to your             index and ready to tracked.
git commit -am : it committing ALL CHANGES including git add and git commit.
 git commit -m : it committing only ADDED CHANGES. not all changes.
git add:  it adds files changes in your working directory to your index.
git remove :it removes files from your working directory and index so that they will not tracked again.
git push: it pushes all the  modified LOCAL OBJECTS to the REMOTE REPOSITORY.
